management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    loggers:
      enabled: true
    mappings:
      enabled: true